name: "Convert issues to markdowns"
on:
  workflow_dispatch:
    
jobs:
  convert_issues_to_markdown_job:
    runs-on: ubuntu-latest
    name: Convert issues to markdowns.
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Fetch issues and generate markdowns
        uses: skyfe79/hugo-with-github-issues@v1.3
        with:
          github-token: ${{ secrets.toot }}
          repo: 'test2'
          owner: 'stevefaulkner'
          skip-author: 'utterances-bot'
          skip-pull-requests: 'true'
          use-issue-seperator: 'true'
          output: 'content/posts'
      - name: Commit files
        run: |
          git config --local user.email "sfaulkner@gmail.com"
          git config --local user.name "steve faulkner"
          git add .
          git commit -m "Add Issues"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.toot }}
          branch: ${{ github.ref }}
