name: CI
on: workflow_dispatch
jobs:
  deploy:
    name: Export issues to S3
    runs-on: ubuntu-latest
    steps:
    - name: Export issues
      uses: niteoweb/export-issues-action@v2
      with:
        repo: ${{ github.test2 }}
        org: ${{ github.stevefaulkner }}
        repo-token: ${{ secrets.TOOT }}
        out: issues
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: issues
        path: "issues/*.md"
